name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.1.15
        poetry --version
        poetry config experimental.new-installer false
        poetry config virtualenvs.create false
        poetry install -vv
        cp .env-sample .env
    - name: Test with pytest
      run: pytest -vvv
