name: Agendamento de postagens de tweets
on:
  schedule:
    # todos os dias às 08 horas do Brasil (11:00:00 UTC)
    - cron: '0 11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configura o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executa script python
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          MARIA_QUITERIA_API_URL: ${{ secrets.MARIA_QUITERIA_API_URL }}
          MARIA_QUITERIA_API_TOKEN: ${{ secrets.MARIA_QUITERIA_API_TOKEN }}
        run: python main.py
