name: Agendamento de postagens de tweets
on:
  workflow_dispatch:
  schedule:
    # todos os dias às 08 horas do Brasil (11:00:00 UTC)
    - cron: '0 11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configura o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.15
          poetry --version
          poetry config experimental.new-installer false
          poetry config virtualenvs.create false
          poetry install -vv
      - name: Executa script python
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          MARIA_QUITERIA_API_HOST: ${{ secrets.MARIA_QUITERIA_API_HOST }}
          MARIA_QUITERIA_USERNAME: ${{ secrets.MARIA_QUITERIA_USERNAME }}
          MARIA_QUITERIA_PASSWORD: ${{ secrets.MARIA_QUITERIA_PASSWORD }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: diario_bot
